In [3]:
import numpy as np

In [4]:
k = 3

ns = np.array([10, 10, 10])
ps = np.array([6, 6, 7])

acc = 0.76

In [5]:
Q = np.diag((ps + ns)**2/(2*ps*ns)/k*2)
q = (ps + ns)**2/(2*ps*ns)/k*2
G = np.vstack([np.eye(k), -np.eye(k)]).astype(float)
h = np.hstack([np.repeat(1.0, k), np.repeat(0.0, k)])
A = np.repeat(1.0/k, k).reshape(-1, 1).T
b = np.array([acc])

In [6]:
Q, q, G, h, A, b

(array([[1.42222222, 0.        , 0.        ],
        [0.        , 1.42222222, 0.        ],
        [0.        , 0.        , 1.37619048]]),
 array([1.42222222, 1.42222222, 1.37619048]),
 array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [-1., -0., -0.],
        [-0., -1., -0.],
        [-0., -0., -1.]]),
 array([1., 1., 1., 0., 0., 0.]),
 array([[0.33333333, 0.33333333, 0.33333333]]),
 array([0.76]))

In [7]:
from cvxopt import matrix
from cvxopt.solvers import qp

In [8]:
Q = matrix(Q)
q = matrix(q)
G = matrix(G)
h = matrix(h)
A = matrix(A)
b = matrix(b)

In [9]:
res = qp(P=Q, q=q, G=G, h=h, A=A, b=b)

     pcost       dcost       gap    pres   dres
 0:  4.4256e+00  1.0042e+00  3e+00  0e+00  5e-16
 1:  4.4253e+00  4.3717e+00  5e-02  1e-16  1e-16
 2:  4.4250e+00  4.4243e+00  7e-04  2e-16  4e-16
 3:  4.4250e+00  4.4250e+00  7e-06  0e+00  4e-16
 4:  4.4250e+00  4.4250e+00  7e-08  1e-16  2e-16
Optimal solution found.


In [10]:
res

{'x': <3x1 matrix, tc='d'>,
 'y': <1x1 matrix, tc='d'>,
 's': <6x1 matrix, tc='d'>,
 'z': <6x1 matrix, tc='d'>,
 'status': 'optimal',
 'gap': 7.463857539398303e-08,
 'relative gap': 1.6867361958144857e-08,
 'primal objective': 4.425029642344141,
 'dual objective': 4.4250295677055655,
 'primal infeasibility': 1.1102230246251565e-16,
 'dual infeasibility': 2.0871597063187184e-16,
 'primal slack': 0.20118636047226765,
 'dual slack': 1.2667384555636575e-08,
 'iterations': 4}

In [11]:
np.array(res['x'])

array([[0.74059318],
       [0.74059318],
       [0.79881364]])

In [12]:
matrix = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0]])

In [13]:
np.linalg.det(matrix)

np.float64(1.0)

In [14]:
from cvxopt import log

In [15]:
k = 2
F = matrix(np.array([[1.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [0.0, 1.0]]).T)
g = log(matrix([[1.0, 1.0]]))
G = matrix(np.array([[1.0, 0.0, 0.0, 0.0],
                     [0.0, 1.0, 0.0, 0.0],
                     [0.0, 0.0, 1.0, 0.0],
                     [0.0, 0.0, 0.0, 1.0],
                     [-1.0, 0.0, 0.0, 0.0],
                     [0.0, -1.0, 0.0, 0.0],
                     [0.0, 0.0, -1.0, 0.0],
                     [0.0, 0.0, 0.0, -1.0]]))
h = matrix(np.array([[1.0],
                     [1.0],
                     [1.0],
                     [1.0],
                     [0.0],
                     [0.0],
                     [0.0],
                     [0.0]]))
A = matrix(np.array([[1.0, 1.0, 0.0, 0.0],
                     [0.0, 0.0, 1.0, 1.0]])*0.5)
b = matrix(np.array([0.7, 0.8]))
K = [2]

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
res = gp(K=K, F=F, g=g, G=G, h=h, A=A, b=b)

     pcost       dcost       gap    pres   dres
 0:  0.0000e+00 -3.3069e+00  9e+00  1e+00  1e+00
 1:  2.1872e+00  6.8052e-01  2e+00  5e-03  5e-03
 2:  2.1931e+00  2.1657e+00  3e-02  5e-05  5e-05
 3:  2.1931e+00  2.1929e+00  3e-04  5e-07  5e-07
 4:  2.1931e+00  2.1931e+00  3e-06  5e-09  5e-09
 5:  2.1931e+00  2.1931e+00  3e-08  5e-11  5e-11
Optimal solution found.


In [ ]:
res

{'status': 'optimal',
 'x': <4x1 matrix, tc='d'>,
 'y': <2x1 matrix, tc='d'>,
 'znl': <0x1 matrix, tc='d'>,
 'zl': <8x1 matrix, tc='d'>,
 'snl': <0x1 matrix, tc='d'>,
 'sl': <8x1 matrix, tc='d'>,
 'gap': 2.780709422080815e-08,
 'relative gap': 1.2679082744004168e-08,
 'primal objective': 2.193147180502576,
 'dual objective': 2.1931471528536157,
 'primal slack': 1.0076478106767936e-10,
 'dual slack': 2.329696361598543e-09,
 'primal infeasibility': 4.952293127842303e-11,
 'dual infeasibility': 4.952313743584385e-11}

In [ ]:
np.array(res['x'])

array([[0.7],
       [0.7],
       [0.8],
       [0.8]])

In [ ]:
sens = 0.7
spec = 0.8

areas = []

for _ in range(1000):
    sens0 = np.random.random()
    spec0 = np.random.random()
    sens1 = sens*2 - sens0
    spec1 = spec*2 - spec0
    if sens1 > 1 or spec1 > 1 or sens1 < 0 or spec1 < 0:
        continue

    area = (sens0*spec0 + sens1*spec1)/2.0
    areas.append((area, sens0, sens1, spec0, spec1))

In [ ]:
amin = np.min([area[0] for area in areas])
amax = np.max([area[0] for area in areas])
amin, amax

(np.float64(0.5047032862474816), np.float64(0.6154901758412835))

In [ ]:
for area in areas:
    if area[0] == amin:
        print('min', area)
    if area[0] == amax:
        print('min', area)

min (0.6154901758412835, 0.9807841130675344, 0.4192158869324655, 0.9976257674804306, 0.6023742325195695)
min (0.5047032862474816, 0.4206394113387292, 0.9793605886612707, 0.9979402821905079, 0.6020597178094922)


In [26]:
def smo_inner(xa, xb, ya, yb):
    c = xa + xb
    mi = max(0, c-1)
    ma = min(1, c)

    if mi * (yb - ya) + c * ya < ma * (yb - ya) + c * ya:
        xb = mi
    else:
        xb = ma

    xa = c - xb

    return xa, xb

def smo(xs, ys):
    idxa, idxb = np.random.choice(list(range(len(xs))), 2, replace=False)
    xa = xs[idxa]
    xb = xs[idxb]
    ya = ys[idxa]
    yb = ys[idxb]

    if np.random.randint(2) == 0:
        print('x')

        xa, xb = smo_inner(xa, xb, ya, yb)        
        
        xs[idxa] = xa
        xs[idxb] = xb
    else:
        print('y')
        
        ya, yb = smo_inner(ya, yb, xa, xb)

        ys[idxa] = ya
        ys[idxb] = yb
    
        

In [27]:
xs = [0.7] * 5
ys = [0.8] * 5

for _ in range(100):
    smo(xs, ys)
    print(np.mean(xs), np.mean(ys), xs, ys, np.mean([x*y for x, y in zip(xs, ys)]))

y
0.7 0.8 [0.7, 0.7, 0.7, 0.7, 0.7] [0.8, 0.6000000000000001, 0.8, 1, 0.8] 0.56
y
0.7 0.8 [0.7, 0.7, 0.7, 0.7, 0.7] [1, 0.6000000000000001, 0.6000000000000001, 1, 0.8] 0.56
y
0.7 0.8 [0.7, 0.7, 0.7, 0.7, 0.7] [1, 1, 0.6000000000000001, 0.6000000000000001, 0.8] 0.5599999999999999
x
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1.0, 0.7] [1, 1, 0.6000000000000001, 0.6000000000000001, 0.8] 0.536
y
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1.0, 0.7] [1, 1, 0.6000000000000001, 0.6000000000000001, 0.8] 0.536
x
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1, 0.7] [1, 1, 0.6000000000000001, 0.6000000000000001, 0.8] 0.536
y
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1, 0.7] [1, 1, 1, 0.20000000000000018, 0.8] 0.512
y
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1, 0.7] [1, 1, 1, 0.20000000000000018, 0.8] 0.512
y
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1, 0.7] [1, 1, 0.8, 0.20000000000000018, 1] 0.5119999999999999
y
0.7 0.8 [0.3999999999999999, 0.7, 0.7, 1, 0.7] [1, 1, 1, 2.220446049250313e-16, 1] 0.5
x
0.7 0.8 [1, 0.7, 0

In [24]:
np.mean(np.array([0.0, 1.0, 0.7, 1.0, 0.8]) * np.array([0.0, 1.0, 1.0, 1.0, 1.0]))

np.float64(0.7)

In [416]:
n = 2
tmp1 = np.eye(n)
tmp0 = np.zeros((n, n))
Q = np.vstack([np.hstack([tmp0, tmp1]), np.hstack([tmp1, tmp0])])
q = np.repeat(0.0, 2*n).reshape((1, -1)).T
G = np.vstack([np.eye(2*n), -np.eye(2*n)]).astype(np.double)
h = np.hstack([np.repeat(1.0, 2*n), np.repeat(0.0, 2*n)])
#G = np.vstack([-np.eye(2*n)]).astype(np.double)
#h = np.hstack([np.repeat(0.0, 2*n)])
A = np.vstack([np.hstack([np.repeat(1.0, n), np.repeat(0.0, n)]), np.hstack([np.repeat(0.0, n), np.repeat(1.0, n)])])/n
b = np.array([0.7, 0.816666])

In [402]:
Q

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [403]:
#Q[0, 0] = 1.0

In [417]:
np.linalg.eig(Q)[0]

array([ 1., -1.,  1., -1.])

In [405]:
G

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [-1., -0., -0., -0.],
       [-0., -1., -0., -0.],
       [-0., -0., -1., -0.],
       [-0., -0., -0., -1.]])

In [406]:
h

array([1., 1., 1., 1., 0., 0., 0., 0.])

In [407]:
q

array([[0.],
       [0.],
       [0.],
       [0.]])

In [408]:
A

array([[0.5, 0.5, 0. , 0. ],
       [0. , 0. , 0.5, 0.5]])

In [409]:
b

array([0.7     , 0.816666])

In [410]:
from cvxopt.solvers import qp, cp, gp
from cvxopt import matrix

In [411]:
Q = matrix(Q, (2*n, 2*n))
q = matrix(q, (2*n, 1))
G = matrix(G)
h = matrix(h)
A = matrix(A)
b = matrix(b)

In [415]:
np.linalg.eig(Q)

EigResult(eigenvalues=array([ 1., -1.,  1., -1.]), eigenvectors=array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678]]))

In [412]:
res = qp(P=Q, q=q, G=G, h=h, A=A, b=b)

     pcost       dcost       gap    pres   dres
 0:  1.1433e+00 -3.5622e+00  5e+00  1e-16  1e-15
 1:  1.1433e+00  1.0963e+00  5e-02  3e-16  6e-16
Terminated (singular KKT matrix).


In [414]:
np.array(res['x'])

array([[0.7     ],
       [0.7     ],
       [0.816666],
       [0.816666]])

In [315]:
q

<4x1 matrix, tc='d'>

In [316]:
res = gp(K=[2*n], F=Q, g=q, G=G, h=h, A=A, b=b)

     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  1.3863e+00  5e+00  1e+00  1e+00
 1:  6.2725e-01 -1.1522e-01  8e-01  7e-03  7e-03
 2:  6.2964e-01  6.2057e-01  9e-03  7e-05  7e-05
 3:  6.2966e-01  6.2957e-01  9e-05  7e-07  7e-07
 4:  6.2966e-01  6.2966e-01  9e-07  7e-09  7e-09
 5:  6.2966e-01  6.2966e-01  9e-09  7e-11  7e-11
Optimal solution found.


In [317]:
res['status']

'optimal'

In [318]:
np.array(res['x'])

array([[0.7     ],
       [0.7     ],
       [0.816666],
       [0.816666]])

In [296]:
np.linalg.det(np.array(Q))

np.float64(1.0)

In [301]:
res = qp(P=Q, q=q, G=G, h=h, A=A, b=b)

ValueError: Rank(A) < p or Rank([P; A; G]) < n

In [ ]:
np.array(res['x'])

array([[3.19299199e-09],
       [1.40000000e+00],
       [1.63333200e+00],
       [2.40948267e-09]])

In [ ]:
res

{'x': <4x1 matrix, tc='d'>,
 'y': <2x1 matrix, tc='d'>,
 's': <4x1 matrix, tc='d'>,
 'z': <4x1 matrix, tc='d'>,
 'status': 'optimal',
 'gap': 5.693156853249831e-08,
 'relative gap': None,
 'primal objective': 8.588491713624935e-09,
 'dual objective': -4.8343076818873306e-08,
 'primal infeasibility': 6.280369834735114e-16,
 'dual infeasibility': 4.9650683065029545e-16,
 'primal slack': 2.409482665308534e-09,
 'dual slack': 1.5770030456142635e-08,
 'iterations': 5}